# Generated by Django 6.0.2 on 2026-02-10 10:49

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Название оборудования')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание (для главной)')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='equipment/main/', verbose_name='Основное фото (на главной)')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='equipment/backgrounds/', verbose_name='Фото на задний фон')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание оборудования')),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Отрасль применения',
                'verbose_name_plural': 'Отрасли применения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Реализованный проект',
                'verbose_name_plural': 'Реализованные проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Тэги (через запятую)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото человека')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Подпись к ФИО')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв клиента',
                'verbose_name_plural': 'Отзывы клиентов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='data.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Преимущество оборудования',
                'verbose_name_plural': 'Преимущества оборудования',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('image', models.ImageField(upload_to='equipment/photos/', verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Заголовок фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание фото')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='data.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Фотография оборудования',
                'verbose_name_plural': 'Фотографии оборудования',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentTechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
                ('image', models.FileField(blank=True, null=True, upload_to='equipment/specs/', verbose_name='Прикрепленное фото (SVG)')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specs', to='data.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'Техническая характеристика оборудования',
                'verbose_name_plural': 'Технические характеристики оборудования',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='data.industry', verbose_name='Отрасли применения'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='equipment', to='data.review', verbose_name='Отзывы клиентов'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta Description')),
                ('short_description', models.TextField(blank=True, verbose_name='Короткое описание (для карточки)')),
                ('icon', models.FileField(blank=True, null=True, upload_to='services/icons/', verbose_name='Иконка (SVG)')),
                ('video_background', models.FileField(blank=True, null=True, upload_to='services/videos/', verbose_name='Видео на задний фон')),
                ('image_background', models.ImageField(blank=True, null=True, upload_to='services/backgrounds/', verbose_name='Фото на задний фон')),
                ('description_image', models.ImageField(blank=True, null=True, upload_to='services/descriptions/', verbose_name='Фото на описание')),
                ('tags', models.CharField(blank=True, max_length=500, verbose_name='Тэги (через запятую)')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание услуги')),
                ('industries', models.ManyToManyField(blank=True, related_name='services', to='data.industry', verbose_name='Отрасли применения')),
                ('projects', models.ManyToManyField(blank=True, related_name='services', to='data.project', verbose_name='Реализованные проекты')),
                ('reviews', models.ManyToManyField(blank=True, related_name='services', to='data.review', verbose_name='Отзывы клиентов')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='data.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Преимущество услуги',
                'verbose_name_plural': 'Преимущества услуг',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTechnicalSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок вывода')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
                ('image', models.FileField(blank=True, null=True, upload_to='services/specs/', verbose_name='Прикрепленное фото (SVG)')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_specs', to='data.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Техническая характеристика услуги',
                'verbose_name_plural': 'Технические характеристики услуг',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
