# Generated by Django 6.0.2 on 2026-02-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, verbose_name='Название услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Тэги (через запятую)'),
        ),
    ]
