# Generated by Django 6.0.2 on 2026-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_service_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, verbose_name='Название услуги'),
        ),
    ]
