# Generated by Django 6.0.2 on 2026-02-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_equipment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Тэги (через запятую)'),
        ),
    ]
