# Generated by Django 6.0.2 on 2026-02-14 15:10

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.TextField(blank=True, null=True, verbose_name='TITLE')),
                ('page_description', models.TextField(blank=True, null=True, verbose_name='DESCRIPTION')),
                ('order_num', models.IntegerField(default=1, null=True)),
                ('cover', models.ImageField(null=True, upload_to='news/images', verbose_name='Картинка превью')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('slug', models.CharField(blank=True, editable=False, help_text='Если не заполнено, создается на основе поля Назавание', max_length=255, null=True, verbose_name='ЧПУ')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Редактор')),
                ('show_on_main', models.BooleanField(default=False, verbose_name='Показывать на главной')),
                ('created', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('order_num',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='news/images', verbose_name='Картинка')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.newsitem')),
            ],
        ),
    ]
