# Generated by Django 6.0.2 on 2026-02-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_newsitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Тэги (через запятую)'),
        ),
    ]
