# Generated by Django 6.0.2 on 2026-02-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_newsitem_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Короткое описание'),
        ),
    ]
