# Generated by Django 6.0.2 on 2026-02-15 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_newsitem_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(null=True, upload_to='news/images', verbose_name='Картинка')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='data.project')),
            ],
        ),
    ]
