# Generated by Django 6.0.2 on 2026-02-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Фото человека'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подпись к ФИО'),
        ),
    ]
