# Generated by Django 6.0.2 on 2026-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_newsitem_full_name_newsitem_photo_newsitem_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Имя')),
                ('company', models.CharField(max_length=255, null=True, verbose_name='Наименование компании')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Почта')),
                ('file', models.FileField(blank=True, null=True, upload_to='forms', verbose_name='Карточка предприятия')),
                ('is_done', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
