# Generated by Django 6.0.2 on 2026-02-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_callbackform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта'),
        ),
    ]
