# Generated by Django 6.0.2 on 2026-02-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_alter_callbackform_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Фото человека')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Подпись к ФИО')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команда',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='ment_title',
            field=models.TextField(blank=True, verbose_name='Meta Title'),
        ),
        migrations.AddField(
            model_name='service',
            name='show_video',
            field=models.BooleanField(blank=True, default=False, verbose_name='показывать видеоплеер'),
        ),
        migrations.AddField(
            model_name='service',
            name='vk_video',
            field=models.TextField(blank=True, null=True, verbose_name='VK видео'),
        ),
    ]
