# Generated by Django 6.0.2 on 2026-03-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_team_service_ment_title_service_show_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetechnicalspec',
            name='image',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='services/specs/', verbose_name='Прикрепленное фото (SVG)'),
        ),
    ]
