# Generated by Django 6.0.2 on 2026-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_alter_servicetechnicalspec_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_background_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='services/backgrounds/', verbose_name='Фото на задний фон mobile'),
        ),
        migrations.AlterField(
            model_name='servicetechnicalspec',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='services/specs/', verbose_name='Прикрепленное фото (SVG)'),
        ),
    ]
