# Generated by Django 6.0.2 on 2026-03-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0015_service_image_background_mobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_background_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/backgrounds/', verbose_name='Фото на задний фон mobile'),
        ),
    ]
