# Generated by Django 6.0.2 on 2026-03-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_equipment_image_background_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='show_at_index',
            field=models.BooleanField(blank=True, default=True, verbose_name='На главной'),
        ),
    ]
