# Generated by Django 6.0.2 on 2026-03-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_servicestep'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_at_index',
            field=models.BooleanField(blank=True, default=True, verbose_name='На главной'),
        ),
    ]
