# Generated by Django 6.0.2 on 2026-03-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_alter_service_options_service_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callbackform',
            name='company',
        ),
        migrations.AddField(
            model_name='callbackform',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коммент'),
        ),
    ]
