# Generated by Django 6.0.2 on 2026-03-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0021_remove_callbackform_company_callbackform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ment_title',
            field=models.TextField(blank=True, verbose_name='Meta Title'),
        ),
    ]
